version: '2'

networks:
  pnindex_network:
    #external:
    #  name: nginxproxynetwork
    external: false

volumes:
  pnindex_es:

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    volumes:
    #  - pnindex_es:/usr/share/elasticsearch/data
      - ./index:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - pnindex_network

  kibana:
      image: docker.elastic.co/kibana/kibana:7.5.2
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
        ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'    
      ports:
        - 5601:5601 
      networks:
        - pnindex_network         

  #app:
  #  build:
  #     context: ./app
  #     dockerfile: Dockerfile.dev
  #  environment:
  #     - VIRTUAL_HOST=pnindex.sd.di.huc.knaw.nl
  #  ports:
  #     - 5000:5000
  #  networks:
  #     - pnindex_network