@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Entity" as e {
  *_id : number <<generated>>
  --
  *name : text
  *category: {'Persoon', 'Commissie', 'Instelling', 'Hoedanigheid'}
  ' hints are years in general
  activity_hint_begin: text 
  activity_hint_end: text
  provenance: uri
  
}

entity "Label" as l {
  *_id : number <<generated>>
  --
  *label : text
}

entity "Persoon" as p {
  'same id as the corresponding entity
  *_id : number
  --
  period_start : number
  period_end : number
  life_begin: number
  life_end: number
  province : text
}
}

e }|-{l

@enduml

